### PR TITLE
Retrieve dataset name from mountpoint instead of commandline option

### PR DESCRIPTION
**Pull request by Mic92**
This patch will:
- check on which filesystem the directory '/var/lib/docker' is located  
- if its a zfs get the dataset name from /proc/mounts

reason:
- Some distribution have no configuration to pass commandline options to docker:
  ex: ./contrib/init/systemd/docker.service
  docker should work without editing init configuration
- this way one also could create an additional dataset where all docker volumes are included ('data/docker' instead 'data'), which allow to set additional zfs options for docker volumes through inheritance
- currently docker fails with an error message if libzfs is available, when it tries the zfs driver, because the zfs pool 'docker' is not available

### CODE REVIEW

**Comment by baloo** [comment]
I strongly prefer the `--storage-opts` option. You will have to set the `-s zfs` in `contrib/init/systemd/docker.service` anyway.

That said, I like the two other commits (but I think `FsMagicZfs   = FsMagic(0x2fc12fc1)` in the third commit should be in the second one).

Could you please split this PR in two PRs ?

**Comment by Mic92** [comment]
How about best of both world? If `--storage-opts` is present, use it, otherwise get dataset name from `/var/lib/docker`. The last one will be consistent compared to the btrfs driver. So "-s zfs" can be set, but don't have to.

**Comment by baloo** [comment]
Looks like a plan

**Comment by Mic92** [comment]
Do still want separate Pull-Requests? (the last 3 Commits depends on the 2 second Commit anyway)

**Comment by baloo** [comment]
I'll try to have this merged over the weekend along with the `--storage-opts` we discussed.

**Comment by Mic92** [comment]
I have already implemented `storage-opts` as you wanted it

**Pull request merged**
